-- Generated from generator/demo_specs/aws-philippines-banking-lending.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-philippines-banking-lending
-- This is the schema that is actually deployed for PH_BANKING_LENDING.

-- Alerts fire on the top tail of NPL Ratio
-- (higher is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.91) WITHIN GROUP (ORDER BY KPI_NPL_RATIO) AS T
  FROM RAW.BANK_STATEMENTS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_NPL_RATIO >= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_NPL_RATIO), 2) AS AVG_NPL_RATIO,
  ROUND(AVG(f.KPI_MIGRATION_TO_STAGE_2), 2) AS AVG_MIGRATION_TO_STAGE_2,
  ROUND(AVG(f.KPI_COLLECTION_RATE), 2) AS AVG_COLLECTION_RATE
FROM RAW.BANK_STATEMENTS f
JOIN RAW.COLLECTIONS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_NPL_RATIO), 2) AS AVG_NPL_RATIO,
  ROUND(AVG(f.KPI_MIGRATION_TO_STAGE_2), 2) AS AVG_MIGRATION_TO_STAGE_2,
  ROUND(AVG(f.KPI_COLLECTION_RATE), 2) AS AVG_COLLECTION_RATE
FROM RAW.BANK_STATEMENTS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_NPL_RATIO) AS KPI_NPL_RATIO, AVG(KPI_MIGRATION_TO_STAGE_2) AS KPI_MIGRATION_TO_STAGE_2, AVG(KPI_COLLECTION_RATE) AS KPI_COLLECTION_RATE FROM RAW.BANK_STATEMENTS),
     en AS (SELECT SUM(KPI_LOAN_PORTFOLIO) AS KPI_LOAN_PORTFOLIO, SUM(KPI_DISBURSEMENTS_MTD) AS KPI_DISBURSEMENTS_MTD, SUM(KPI_BORROWERS_ACTIVE) AS KPI_BORROWERS_ACTIVE, SUM(KPI_EXPECTED_LOSS) AS KPI_EXPECTED_LOSS FROM RAW.COLLECTIONS)
  SELECT 1 AS SORT_ORDER, 'Loan Portfolio' AS TITLE, KPI_LOAN_PORTFOLIO AS VALUE_NUM, '₱' || TO_VARCHAR(CAST(ROUND(((KPI_LOAN_PORTFOLIO) / 1000000000)) AS DECIMAL(38,0))) || 'B' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'NPL Ratio' AS TITLE, KPI_NPL_RATIO AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_NPL_RATIO), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Disbursements (MTD)' AS TITLE, KPI_DISBURSEMENTS_MTD AS VALUE_NUM, '₱' || TO_VARCHAR(CAST(ROUND(((KPI_DISBURSEMENTS_MTD) / 1000000000), 1) AS DECIMAL(38,1))) || 'B' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Borrowers Active' AS TITLE, KPI_BORROWERS_ACTIVE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_BORROWERS_ACTIVE) / 1000000), 1) AS DECIMAL(38,1))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Expected Loss' AS TITLE, KPI_EXPECTED_LOSS AS VALUE_NUM, '₱' || TO_VARCHAR(CAST(ROUND(((KPI_EXPECTED_LOSS) / 1000000000), 1) AS DECIMAL(38,1))) || 'B' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Migration to Stage 2' AS TITLE, KPI_MIGRATION_TO_STAGE_2 AS VALUE_NUM, '+' || TO_VARCHAR(CAST(ROUND((KPI_MIGRATION_TO_STAGE_2), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Collection Rate' AS TITLE, KPI_COLLECTION_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_COLLECTION_RATE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
