-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Digital Lending & Credit Scoring Platform
-- ============================================================================
USE DATABASE DIGITAL_LENDING;
USE SCHEMA ML;

-- ML.CLASSIFICATION: CREDIT_SCORER
CREATE OR REPLACE SNOWFLAKE.ML.CLASSIFICATION ML.CREDIT_SCORER(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.CREDIT_FEATURES'),
  TARGET_COLNAME => 'DEFAULT_90D'
);

-- ML.CLASSIFICATION: COLLECTION_PRIORITY
CREATE OR REPLACE SNOWFLAKE.ML.CLASSIFICATION ML.COLLECTION_PRIORITY(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.PORTFOLIO_HEALTH'),
  TARGET_COLNAME => 'COLLECTION_OUTCOME'
);

