-- ============================================================================
-- 99_RESET.SQL — Reset Digital Lending & Credit Scoring Platform to clean demo state
-- ============================================================================
USE DATABASE DIGITAL_LENDING;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_BUILD_360 SUSPEND;
ALTER TASK IF EXISTS APP.TASK_SCORE_APPLICANTS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_MONITOR_PORTFOLIO SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.APPLICANT_360 REFRESH;
ALTER DYNAMIC TABLE CURATED.PORTFOLIO_HEALTH REFRESH;
ALTER DYNAMIC TABLE CURATED.CREDIT_FEATURES REFRESH;
ALTER DYNAMIC TABLE CURATED.DECISION_METRICS REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM DIGITAL_LENDING.RAW.APPLICATIONS → 450000
-- SELECT COUNT(*) FROM DIGITAL_LENDING.RAW.BANK_STATEMENTS → 1200000
-- SELECT COUNT(*) FROM DIGITAL_LENDING.CURATED.APPLICANT_360 → 450000

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_MONITOR_PORTFOLIO RESUME;
ALTER TASK IF EXISTS APP.TASK_SCORE_APPLICANTS RESUME;
ALTER TASK IF EXISTS APP.TASK_BUILD_360 RESUME;
